CREATE TABLE ROUTES
(id BIGINT AUTO_INCREMENT PRIMARY KEY,
 NAME VARCHAR(30) UNIQUE NOT NULL,
 LENGTH VARCHAR(30),
 CHECKPOINTS VARCHAR(32000) NOT NULL,
 SKILL TINYINT NOT NULL,
 TYPE VARCHAR(30),
 ELEVATION VARCHAR(30));
